name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      WORKSPACE: ${{ github.workspace }}
      CSPROJ: ${{ github.workspace }}\Securify.PropertyStore.csproj
      GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup Scoop
      run: |
        if(-not (Test-Path $env:CSPROJ -ErrorAction Stop)) { throw "${env:CSPROJ} does not exist." }
        try {
          git config --global user.email "ninja@thesharp.ninja"
          git config --global user.name "GitHub on behalf of Sharp Ninja"
          git fetch --unshallow
          iwr -useb get.scoop.sh | iex
          scoop install gitversion

          if(-not (Test-Path GitVersion.yml)) {
            $yml = @(
              'assembly-versioning-scheme: MajorMinorPatch',
              'mode: ContinuousDelivery',
              'next-version: 1.2.0',
              'branches: {}',
              'ignore:',
              '  sha: []',
              'merge-message-formats: {}'
            )

            $yml | out-file GitVersion.yml

            git add .
            git commit -m "Added gitversion config."
            git push "https://sharpninja:${env:GITHUB_TOKEN}@github.com/sharpninja/PropertyStore.git"
          }        
          GitVersion
          
        } catch {
          $e=$_
          Write-Error "Error initializing GitVersion."
          Write-Error $e
          throw $e
        }
        
    - name: Install dependencies
      run: dotnet restore
      
#     - name: Setup .NET Core @ Latest
#       uses: actions/setup-dotnet@v1
#       with:
#         source-url: https://nuget.pkg.github.com/sharpninja/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity quiet
      
    - name: Push generated package to GitHub registry
      run: |
        $out="${env:WORKSPACE}\out"
        $packages="${out}\*.nupkg"
        dotnet pack --configuration Release --no-build -o $out
        $pkgs=Get-ChildItem $packages -ErrorAction Stop
        if($pkgs) {
          $nugetConfig = @('<?xml version="1.0" encoding="utf-8"?>',
            '<configuration>',
                '<packageSources>',
                    '<clear />',
                '</packageSources>',
            '</configuration>')
            
          $nugetConfig | Out-File nuget.config
          
          dotnet nuget add source `
            --username sharpninja `
            --password "${env:GITHUB_TOKEN}" `
            --store-password-in-clear-text `
            --name github "https://nuget.pkg.github.com/sharpninja/index.json" `
            --valid-authentication-types basic `
            --configfile nuget.config
            
          get-content nuget.config
            
          dotnet nuget push $pkgs.FullName --skip-duplicate --no-symbols true --verbosity detailed
          # nuget push $pkgs.FullName -ConfigFile nuget.config -Source github -SkipDuplicate -NoSymbols -Verbosity detailed
        } else {
          throw "$pkgs return no results."
        }
